# A simple .yml template locate on <repository/.github/workflows/appdoem_ci.yml>
name: APPDOME_CI_EXAMPLE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: Appdome build-2secure
      uses: Appdome/github_build-2secure@1.0
      with:
        APP_FILE: app/debug/
        FUSION_SET_ID: ${{ secrets.FUSION_SET_ID }}
        SIGN_OPTIONS: "SIGN_ON_APPDOME"
        APPDOME_API_TOKEN: ${{ secrets.APPDOME_API_KEY }}
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASS }}
        
